export const sampleDocuments = [
  {
    id: "sell-my-home",
    displayCategoryName: "Sell My Home",
    seCategoryName: "Home Sale",
    portalTaskId: 1234,
    contentfulIncluded: false,
    subCategories: [
      {
        id: "broker-market-analysis",
        displaySubCategoryName: "Broker Market Analysis",
        seSubCategoryName: "Graebel HS BMA Order",
        parentCategoryId: "sell-my-home",
        contentfulIncluded: false,
        documents: [
          {
            documentTransactionalId: 202591,
            title: "Passport",
            fileDate: "2026-04-22T20:01:04.747",
            fileSize: 670536,
            fileType: "pdf",
            contentType: "",
            serviceCategory: "Home Sale",
            subCategory: "Graebel HS BMA Order",
            workflowName: "Home Sale",
            status: "",
          },
          {
            documentTransactionalId: 202590,
            title: "Expense report",
            fileDate: "2026-04-22T20:00:16.14",
            fileSize: 188761,
            fileType: "pdf",
            contentType: "",
            serviceCategory: "Home Sale",
            subCategory: "Graebel HS BMA Order",
            workflowName: "Home Sale",
            status: "",
          },
        ],
      },
      {
        id: "equity",
        displaySubCategoryName: "Equity",
        seSubCategoryName: "Graebel HS Equity Statement",
        parentCategoryId: "sell-my-home",
        contentfulIncluded: false,
        documents: [
          {
            documentTransactionalId: 202594,
            title: "Equity Documents",
            fileDate: "2026-04-22T20:05:27.887",
            fileSize: 13721,
            fileType: "docx",
            contentType: "",
            serviceCategory: "Home Sale",
            subCategory: "Graebel HS Equity Statement",
            workflowName: "Home Sale",
            status: "",
          },
        ],
      },
      {
        id: "offer-agreements",
        displaySubCategoryName: "Offer Agreements",
        seSubCategoryName: null,
        parentCategoryId: "sell-my-home",
        contentfulIncluded: false,
        documents: null,
      },
    ],
    documents: null,
  },
  {
    id: "destination-services",
    displayCategoryName: "Destination Services",
    seCategoryName: "Destination Services",
    portalTaskId: 1235,
    contentfulIncluded: false,
    subCategories: [
      {
        id: "rental-assistance",
        displaySubCategoryName: "Rental Assistance",
        seSubCategoryName: "Graebel Destination Services",
        parentCategoryId: "destination-services",
        contentfulIncluded: false,
        documents: [
          {
            documentTransactionalId: 203136,
            title: "Rental Lease Agreement",
            fileDate: "2026-05-05T15:02:38.703",
            fileSize: 670536,
            fileType: "pdf",
            contentType: "",
            serviceCategory: "Destination Services",
            subCategory: "Graebel Destination Services",
            workflowName: "Destination Services",
            status: "",
          },
        ],
      },
      {
        id: "temporary-living",
        displaySubCategoryName: "Temporary Living",
        seSubCategoryName: "Graebel Temporary Living Service Order",
        parentCategoryId: "destination-services",
        contentfulIncluded: false,
        documents: [
          {
            documentTransactionalId: 203708,
            title: "temp living lease agreement",
            fileDate: "2026-05-12T21:02:57.91",
            fileSize: 45762,
            fileType: "png",
            contentType: "",
            serviceCategory: "Temporary Living",
            subCategory: "Graebel Temporary Living Service Order",
            workflowName: "Temporary Living",
            status: "",
          },
        ],
      },
    ],
    documents: null,
  },
  {
    id: "lorem-ipsum",
    displayCategoryName: "Lorem Ipsum",
    seCategoryName: "Lorem Ipsum Dolor",
    portalTaskId: 1235,
    contentfulIncluded: false,
    subCategories: null,
    documents: null,
  },
  {
    id: "other-documents",
    displayCategoryName: "Other Documents",
    seCategoryName: null,
    portalTaskId: null,
    contentfulIncluded: false,
    subCategories: null,
    documents: [
      {
        documentTransactionalId: 203709,
        title: "mortgageFlyer1",
        fileDate: "2026-05-12T21:06:36.43",
        fileSize: 161630,
        fileType: "png",
        contentType: "",
        serviceCategory: "",
        subCategory: "",
        workflowName: "",
        status: "",
      },
      {
        documentTransactionalId: 203224,
        title: "Signed PPA",
        fileDate: "2026-05-06T17:45:29.857",
        fileSize: 157800,
        fileType: "docx",
        contentType: "",
        serviceCategory: "",
        subCategory: "",
        workflowName: "",
        status: "",
      },
    ],
  },
];
